spring.application.name=colourpalettebackend
spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=8MB

image.transform.service.url=localhost
image.transform.service.port=50051