spring.application.name=colourpalettebackend
spring.servlet.multipart.max-file-size=32MB
spring.servlet.multipart.max-request-size=32MB

image.transform.service.url=localhost
image.transform.service.port=50051